[package]
name = "rs-stellar-base"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
arrayref = "0.3.7"
lazy_static = "1.4.0"
libsodium-sys = "0.2.7"
num-bigint = "0.4.3"
sha2 = "0.10.7"
stellar-strkey = "0.0.7"

